spring.application.name=english-quiz
spring.liquibase.change-log=classpath:liquibase/master.xml
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

agent.api-key=${AGENT_API_KEY:}
